@baseUrl = http://host.docker.internal:3333

///
/// CATEGORIES
///

### create a category
POST {{baseUrl}}/categories
Content-Type: application/json

{
  "name": "Movie"
}

### list all categories

# @name categories
@categoryId = {{categories.response.body.data.0.id}}

GET {{baseUrl}}/categories

### list a category
GET {{baseUrl}}/categories/{{categoryId}}

### udpate a category
PATCH {{baseUrl}}/categories/{{categoryId}}
Content-Type: application/json

{
  "description": "some description"
}

### delete a category
DELETE {{baseUrl}}/categories/{{categoryId}}


///
/// CAST MEMBERS
///

### create a cast member
POST {{baseUrl}}/cast-members
Content-Type: application/json

{
  "name": "John Doe",
  "type": 1
}

### list all cast members

# @name cast_members
@castMemberId = {{cast_members.response.body.data.0.id}}

GET {{baseUrl}}/cast-members

### list a cast member
GET {{baseUrl}}/cast-members/{{castMemberId}}

### udpate a cast member
PATCH {{baseUrl}}/cast-members/{{castMemberId}}
Content-Type: application/json

{
  "type": 2
}

### delete a cast member
DELETE {{baseUrl}}/cast-members/{{castMemberId}}

///
/// GENRES
///

### create a genre
POST {{baseUrl}}/genres
Content-Type: application/json

{
  "name": "Action",
  "categories_id": ["{{categoryId}}"]
}

### list all genres

# @name genres
@genreId = {{genres.response.body.data.0.id}}

GET {{baseUrl}}/genres

### list a genre
GET {{baseUrl}}/genres/{{genreId}}

### udpate a genre
PATCH {{baseUrl}}/genres/{{genreId}}
Content-Type: application/json

{
  "name": "some description"
}

### delete a genre
DELETE {{baseUrl}}/genres/{{genreId}}


///
/// VIDEOS
///

### create video
POST {{baseUrl}}/videos
Content-Type: application/json

{
  "title": "some title",
  "description": "some description...",
  "year_launched": 2020,
  "duration": 120,
  "rating": "18",
  "is_opened": false,
  "categories_id": ["{{categoryId}}"],
  "genres_id": ["{{genreId}}"],
  "cast_members_id": ["{{castMemberId}}"]
}

### list all videos

# @name videos
@videoId = {{videos.response.body.data.0.id}}

GET {{baseUrl}}/videos

### list a video
GET {{baseUrl}}/videos/{{videoId}}

### udpate a video
PATCH {{baseUrl}}/videos/{{videoId}}
Content-Type: application/json

{
  "title": "some title updated",
  "description": "some description updated",
  "year_launched": 2021,
  "duration": 180,
  "rating": "18",
  "is_opened": true
}
