version: "3"

services:
  app:
    build: .docker/app
    container_name: codeflix-microservice-videos-backend
    command: .docker/app/start.sh
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
