version: "3"

services:
  app:
    build: .
    container_name: codeflix-videos-backend
    # command: .docker/app/start.sh
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  node_modules: {}
