version: "3"

services:
  app:
    build: .
    container_name: codeflix-videos-backend
    command: .docker/app/start.sh
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8.0.39-debian
    container_name: codeflix-videos-db
    restart: always
    tty: true
    ports:
      - "3366:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    security_opt:
      - seccomp:unconfined
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: codeflix-videos-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
